pipeline:
  release:
    image: plugins/docker
    settings:
      repo: "${CI_REPO_OWNER%%io}/${CI_REPO_NAME}"
      tags: ${CI_REPO_TAG##v} # strips v from the tag
    secrets: [docker_username, docker_password]
    when:
      event: tag
      tag: v*
